### model
model_name_or_path: /data1/model_init/Qwen2.5-Coder-7B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 256
lora_alpha: 256
lora_target: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
disable_shuffling: false
dataset: zeta_train
cutoff_len: 8192
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### warmup
freeze_extra_id_steps: 0
extra_id_loss_weight: 1.0

### output
output_dir: /data1/gsn/CustomTrain/output/data_formatting/7b_full_zeta_lora
logging_steps: 5
plot_loss: true
save_steps: 5000
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 2e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
# warmup_ratio: 0.1
bf16: true
weight_decay: 0.01
ddp_timeout: 180000000
resume_from_checkpoint: null

# ### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10