### model
model_name_or_path: /data/mnt_bucket/model_init/Qwen2.5-Coder-3B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 256
lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: perm2k_train
cutoff_len: 6000
max_samples: 70000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### warmup
warmup_dataset_name: perm2k_train_warmup_15k_0.8
warmup_dataset_steps: 300

### output
output_dir: /data/mnt_bucket/qzq/CustomTrain/output/gsn/custom_train_warmup/qzq_run_lora_3b_epoch4_7w
logging_steps: 50
plot_loss: true
save_steps: 500
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 3.0e-4
num_train_epochs: 4.0
lr_scheduler_type: cosine
# warmup_ratio: 0.1
bf16: true
weight_decay: 0.01
ddp_timeout: 180000000
resume_from_checkpoint: null
freeze_extra_id_steps: 500
extra_id_loss_weight: 0.05

# ### eval
eval_dataset: perm2k_valid_fixed_800
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 50